### ISSUE TITLE
`pool()` does not work for `lrm` and `geeglm`

### ISSUE THREAD

**Issue by stefvanbuuren** [amices/mice#106]
Contributed by Gerald Lebovic: 

I have come across an issue in the latest version of the `mice` package (version 3.0.0). Under the previous version (I think 2.3.0) I was able to use the pool function with an lrm object. I now get an error when using it.
 
    Error in as.data.frame.default(x) :
      cannot coerce class ‘c("lrm", "rms", "glm")’ to a data.frame
    In addition: Warning message:
    In tidy.default(X[[i]], ...) : No method for tidying an S3 object of class lrm , using as.data.frameNo method for tidying an S3 object of class rms , using as.data.frame No method for tidying an S3 object of class glm , using as.data.frame
 
I am not sure how to resolve the issue.
 
In addition, the pool function in mice v 2.30 worked with output from the `geeglm` function after specifying the following `vcov` function:
vcov.geeglm <- function(x)summary(x)$cov.scaled
 
However, the `pool` function in `mice 3.0.0` returns the following error in the same situation:
 
    Error in `$<-.data.frame`(`*tmp*`, df.residual, value = 1703L) :
      replacement has 1 row, data has 0
 
Using `traceback()` I was able to narrow down the error to the `glance()` function from the broom package.

**Comment by stefvanbuuren** [comment]
Thanks for reporting. 

`mice 3.0.0` relies on the `broom` package to understand the output created by different `R` functions.  Many standard functions are incorporated into `broom`, but unfortunately `lrm()` and `geeglm()` are not.

You could do various things: 
- Ask the maintainer to contribution the relevant (`glance`, `tidy`) functions to `broom`, 
- Use a function that is supported, e.g., `glm()` instead `lrm()`
- Try to get around `pool()` by doing the extraction yourself and use `pool.scalar()`.

These all have pro's and con's, so select the one that suits your situation best.

**Comment by stefvanbuuren** [comment]
Related to #95

**Comment by ianaianawong** [comment]
> 
Dear Professor van Buuren,

First of all, thank you very much for the creation of `mice `package. 

My study aims to examine multiple parallel mediators between a predictor and an outcome variable. I've used mice to run multiple imputations for the missing data. I would like to use the `PROCESS `function in [`bruceR `](https://cran.r-project.org/web/packages/bruceR/bruceR.pdf)package to conduct the multiple mediation. 

Upon checking the posts on github, I understand that `bruceR `is not incorporated into `broom `so I received error messages after using the mice::pool function. 

I also understand that I can use `pool.scalar()` function to extract the analysis myself. However, I can only find instructions for using `pool.scalar()` for univariate analysis. Since my analysis involves multiple mediators (5 in total), would you please advise on the steps for multivariate analysis? Or would you please direct me to the resources on this? I'm afraid I can't find the relevant guidance online.

**Comment by psychbruce** [comment]
@ianaianawong Let me reiterate my email to you.

Dear Iana,

Thank you for your suggestion. But I'm afraid it is far beyond the scope of PROCESS() and bruceR, and actually cannot address your issue effectively. There might be some misunderstanding of these packages.

(1) "adding the PROCESS codes of bruceR package to the broom package" is impractical and unnecessary, because they are different functions with different purposes developed by different people. I'm not sure if it is correct that "The popular mice package uses broom to pool multiply imputed data". To my knowledge, the broom package actually aims to provide tidy summary of the coefficients of a "model" as a "tibble" (data frame) but not do anything directly related to multiple imputation, while the PROCESS() function by its nature is an interface to build multiple "models" (lm, glm, lmer, or glmer) that are used for mediation/moderation analyses.

Mediation "model" is NOT a real "model" object in R, but multiple "model" objects of class lm, glm, lmer, or glmer (depending on situations). Thus, PROCESS() does not produce a "mediation model", but instead builds multiple linear (mixed) models, which you can extract from its output (i.e., "model.m" and "model.y", as I explained in earlier emails). In other words, you can definitely build these models totally without PROCESS(), because they are just lm, glm, lmer, or glmer "model" objects in nature, NOT a PROCESS "model" object that would be suitable for the broom or mice package to use.

(Not sure if you can understand this difference, but hopefully I have clarified them. It is helpful if you use View() to see what are included in the returned object of PROCESS, which is indeed a list of "models" and other information, not a "model" itself.)

(2) Multiple imputation is INDEPENDENT of and can be conducted BEFORE modeling. You may use the mice package BEFORE you use any function of bruceR (or any other function outside of bruceR). You may prepare an imputed dataset BEFORE any analysis, perhaps with lm(), glm(), lmer(), or glmer() functions for modeling. Again, PROCESS() merely calls these modeling functions but does not build a "mediation model" object for multiple imputation. Indeed, for the multiple mediation model you would test, PROCESS() actually builds multiple "models", one with Y as the outcome and the others with the mediators as the outcomes respectively. To reiterate, a mediation model is NOT literally one statistical "model", but rather a conceptual "model" that involves multiple statistical models.

Thus, any issue should be referred to the lm(), glm(), lmer(), or glmer() functions, not to the PROCESS() function. By imputing missing data BEFORE using PROCESS(), you can of course "run a mediation analysis right after handling the missing data". I was not aware of any barriers to this. Since lm() and glm() have been "incorporated into broom", you should use them with the mice package to impute missing data, instead of using PROCESS() with mice to impute missing data. PROCESS() definitely does not work directly with mice and broom, and it does not have to (as I explained above).

**Comment by stefvanbuuren** [comment]
The `mice::pool()` function requires the parameter estimates from the repeated analyses to be structured. Conventionally, this structuring process relies on the `broom` package and takes place within `pool()` function. In this setup, however, it is difficult to pool parameters estimated by an unsupported analysis function (i.e., for which there is no `tidy()` and `glance()` method). 

The `pool.scalar()` approach is technically correct, but inconvenient because you need to repeat it for each parameter.

I am thinking of another approach that separates the "tidying part" from "reducing parameter estimates part". In fact, in `mice` we can view the parameters exported according to the broom-format, as follows:

``` r
library(mice, warn.conflicts = FALSE)
imp <- mice(nhanes2, print = FALSE)
fit <- with(imp, lm(chl ~ age + bmi + hyp))
summary(fit)
#> # A tibble: 25 × 6
#>    term        estimate std.error statistic  p.value  nobs
#>    <chr>          <dbl>     <dbl>     <dbl>    <dbl> <int>
#>  1 (Intercept)   -39.0      56.2    -0.694  0.495       25
#>  2 age40-59       53.5      18.1     2.95   0.00796     25
#>  3 age60-99       57.8      21.8     2.65   0.0154      25
#>  4 bmi             7.52      1.90    3.95   0.000789    25
#>  5 hypyes         -9.96     18.1    -0.550  0.589       25
#>  6 (Intercept)     3.20     54.0     0.0592 0.953       25
#>  7 age40-59       74.3      20.1     3.70   0.00142     25
#>  8 age60-99       74.2      20.7     3.58   0.00186     25
#>  9 bmi             5.50      1.78    3.09   0.00581     25
#> 10 hypyes        -12.9      16.4    -0.784  0.442       25
#> # ℹ 15 more rows
```

<sup>Created on 2023-08-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Thus, `summary.mira()` extracts the necessary parameter estimates. Of course, extraction fails if there are no relevant `tidy()` and `glance()` method. However, the end-user might still be able to create the table as above and feed this into a (changed) `pool()` function.

@ianaianawong Would you be able to create a table like this?

**Comment by stefvanbuuren** [comment]
The `pool.table()` function is now part of `mice 3.16.3`. From the news:

* **New system-independent method for pooling**: This version introduces a new function `pool.table()` that takes a tidy table of parameter estimates stemming from `m` repeated analyses. The input data must consist of three columns (parameter name, estimate, standard error) and a specification of the degrees of freedom of the model fitted to the complete data. The `pool.table()` function outputs 14 pooled statistics in a tidy form. The primary use of `pool.table()` is to support parameter pooling for techiques that have no `tidy()` or `glance()` methods, either within `R` or outside `R`. The `pool.table()` function also allows for a novel workflows that 1) break apart the traditional `pool()` function into a data-wrangling part and a parameters-reducing part, and 2) does not necessarily depend on classed R objects.

Please give it a try.

**Comment by ianaianawong** [comment]
Hi @stefvanbuuren, thanks a lot! It would be convenient to have the pool_table () function. 

Would you mind providing a bit more information on how to use this new function? Is there any example available?

**Comment by stefvanbuuren** [comment]
Yes, install `mice 3.16.3`:

```r
install.packages("devtools")
devtools::install_github(repo = "amices/mice")
library(mice)
```

and study the documentation and examples at <https://amices.org/mice/reference/pool.table.html>.
