### ISSUE TITLE
Non-equivalence of `formulas` and `predictorMatrix` methods for imputing interactions

### ISSUE THREAD

**Issue by stefvanbuuren** [amices/mice#257]
[Nathaniel Wilson](https://uknowledge.uky.edu/cgi/viewcontent.cgi?article=1234&context=cph_etds) studied various `mice` methods to imputed data where interactions are of scientific interest. 

One of his findings is that the `formulas` and `predictorMatrix` methods yield different results, with `predictorMatrix` being the better alternative. As I intended both interfaces as different ways to specify the same model, I wonder where these differences could come from.

It would be useful to have reproducible example to see what happens.

**Comment by prockenschaub** [comment]
[I had a look](https://github.com/prockenschaub/Misc/blob/master/R/mice.formula/README.md) at the code published by Nathaniel alongside his report. I believe the differences are due to a misspecified `predictorMatrix`, which included the interaction of `x` and `y` (=`xyint`) in the imputation of `y`.

```r

myPredMat
#>        x y.miss z.miss xzint yzint xyint
#> x      0      1      1     1     1     1
#> y.miss 1      0      1     1     0     1
#> z.miss 1      1      0     0     0     1
#> xzint  1      1      1     0     1     1
#> yzint  1      1      1     1     0     1
#> xyint  1      1      1     1     1     0

```

Correct specification of the `predictorMatrix` (together with careful application of random seeds) leads to identical outcomes for the `formulas` and `predictorMatrix` options.

**Comment by stefvanbuuren** [comment]
That's great news. I guess I can close now.

Thanks for taking the plunge...
