### ISSUE TITLE
Mode of the m = n multiple imputations

### ISSUE THREAD

**Issue by tswiebold** [amices/mice#304]
Hello,

I am new to using the function and I have a couple questions:

1. I was wondering if taking the mode (for categorical)/mean or median (for continuous) of the multiple imputations for the variables with missing values is appropriate?

2. In terms of computation power, is it more beneficial to maximize "m" or "maxit?" Ideally, I would like to make both as high as possible, but I am limited by my hardware.

Any help will be greatly appreciated!

Have a great day,
tswiebold

**Comment by gerkovink** [comment]
1. Summarizing the cells of the multiply imputed data sets into a single set defies the purpose of multiple imputation. Stef explains in detail as to why you should never do this in [FIMD v2, paragraph 5.1.2](https://stefvanbuuren.name/fimd/workflow.html).
2. instead of optimising *m* or *maxit*, one could better put effort in a good imputation/nonresponse model. If the analysis/imputation/nonresponse models are congenial, even a moderate *m* and *maxit* would yield valid inferences in most scenarios. E.g. in my research I often find that with `m=5` and `maxit=10` the `mice` algorithm has reached a converged state that yields valid inferences; even for scenarios with large amounts of missingness (i.e. > 50%). Added to this; if your models are wrong, even a large *m* and *maxit* will never yield valid inferences. 

All the best, 

Gerko

**Comment by gerkovink** [comment]
Don't get me wrong: a higher `m` or a larger `maxit` will never hurt. But at a certain point, you're not getting better inferences. You're then using your computer as a room heater.

**Comment by tswiebold** [comment]
@gerkovink Thank you very much for your response! I will have to read over the source you provided!

**Comment by gerkovink** [comment]
Have a look at the [`mice` vignettes](https://www.gerkovink.com/miceVignettes/). They may be helpful when you are starting out with the `mice` algorithm.
