### ISSUE TITLE
parlmice progress bar

### ISSUE THREAD

**Issue by ndsubison2178** [amices/mice#639]
How do I track the progress of MI when I use the parallel mice function `parlmice`. Right now i just see that something is going on, but I have no idea where things are. So love to know if there are option to track the progress when `parlmice` is running.

Thanks.

**Comment by thomvolker** [comment]
By now, `parlmice()` is superseded by `futuremice()`. The latter, however, also does not contain functionality to print progress. This is the case because `futuremice()` simply runs `n.core` instances of `mice` with approximately `m/n.core` imputations per instance. Hence, printing progress would result in a progress bar that is completely progressed from the start. If you insist on a progress bar, you could wrap `mice` in `furrr::future_map()` or `pbapply::pblapply()` and combine the results afterwards.

**Comment by ndsubison2178** [comment]
Thanks. I found out about this after I posted this question. Thank you.
