### ISSUE TITLE
Bug in `as.mids()`

### ISSUE THREAD

**Issue by subjut** [amices/mice#7]
I think there is a bug in as.mids() when initializing the mids object:

```
ini <- mice(data[data[, .imp] == 0, -c(.imp, .id)],
    m = max(as.numeric(data[, .imp])),
    maxit = 0)
```

The call to `max(as.numeric(data[, .imp]))` counts one imputation too much, if the original data is identified by `.imp=0`.
I use `R 3.1.1`.

**Comment by jaminday** [comment]
I'm using version 2.22 of MICE and having this same issue with `as.mids`. The final mids object has one imputation too many, containing some odd values. The 'boys' test included in the source code confirms the `.imp` column in the final mids object is vector 0:6 instead of 0:5.

I had to change to `m = max(as.numeric(data[, .imp])) - 1,` in the code above for it to work properly with my dataset.
